baseURL = 'https://TheThinker0314.github.io/GenAI-news-site/'
languageCode = 'en-us'
title = 'GenAI News Hub | Latest in Generative AI'
theme = 'ananke'
enableRobotsTXT = true

[params]
  description = 'Your daily source for the latest news and trends in Generative AI. Stay updated with AI models, tools, and breakthroughs.'
  custom_css = ["css/custom.css"]
  background_color_class = "bg-black"
  env = "production"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "News"
    url = "/posts/"
    weight = 2
